// generated by Textmapper; DO NOT EDIT

package ast

type Node interface {
	Start() int
	End() int
}

type Pos struct {
	Offset, Endoffset int
}

func (p Pos) Start() int { return p.Offset }
func (p Pos) End() int   { return p.Endoffset }

type JSONValue struct {
	JSONObject  *JSONObject
	EmptyObject *EmptyObject
	JSONArray   *JSONArray
	JSONSTRING  string
	Pos
}

type JSONValueA struct {
	JSONObject  *JSONObject
	EmptyObject *EmptyObject
	JSONArray   *JSONArray
	JSONSTRING  string
	Pos
}

type EmptyObject struct {
	LookaheadEmptyObject *LookaheadEmptyObject
	Pos
}

type LookaheadEmptyObject struct {
	Pos
}

type JSONObject struct {
	LookaheadNotEmptyObject *LookaheadNotEmptyObject
	JSONMemberList          []*Field
	Pos
}

type LookaheadNotEmptyObject struct {
	Pos
}

type JSONArray struct {
	JSONElementList []*JSONValueA
	Pos
}
